import os
from typing import Dict

from jinja2 import BaseLoader, Environment, FileSystemLoader

# Template dir with check
template_dir = os.path.join(os.path.dirname(__file__), "../../templates")
if os.path.exists(template_dir):
    env = Environment(
        loader=FileSystemLoader(template_dir), block_start_string="[%", block_end_string="%]"
    )
else:
    env = Environment(loader=BaseLoader())  # Fallback empty
    print("Warning: templates not found, using fallback.")


async def generate_resume(profile: Dict, job: Dict) -> str:
    """Generate a resume based on profile and job description."""
    # Simple stub implementation
    skills = profile.get("skills", ["Python", "FastAPI", "PostgreSQL"])
    name = profile.get("name", "Candidate")
    job_title = job.get("title", "Software Engineer")
    return f"""
# Resume for {name}

## Target Position: {job_title}

## Skills:
{", ".join(skills)}

## Experience:
- Senior Developer (2022-present)
- Python Developer (2019-2022)

## Education:
- Bachelor's in Computer Science

*Generated by Job Automation Agent*
"""
