[tool:pytest]
addopts = --cov=apps/ --cov-report=term --cov-fail-under=95
testpaths = apps tests/e2e tests/unit
pythonpath = . apps src tests
markers =
    e2e: E2E tests (services up)
    slow: Slow tests
