"""Report generation for repository audit."""

import json
from datetime import datetime
from pathlib import Path
from typing import Union

from .checker import RepositoryAuditor


class ReportGenerator:
    """Generate reports in various formats."""

    def __init__(self, auditor: RepositoryAuditor):
        self.auditor = auditor
        self.results = auditor.results
        self.score = auditor.score()

    def to_json(self, pretty: bool = True) -> str:
        """Generate JSON report."""
        data = {
            "metadata": {
                "timestamp": datetime.utcnow().isoformat() + "Z",
                "repo_path": str(self.auditor.repo_path),
                "total_checks": len(self.results),
            },
            "score": self.score,
            "results": [r.to_dict() for r in self.results],
        }
        if pretty:
            return json.dumps(data, indent=2, ensure_ascii=False)
        return json.dumps(data, separators=(",", ":"), ensure_ascii=False)

    def to_markdown(self) -> str:
        """Generate Markdown report."""
        lines = [
            "# Repository Audit Report",
            "",
            f"**Date**: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}",
            f"**Repository**: `{self.auditor.repo_path}`",
            "",
            "## Summary",
            "",
            f"**Overall Score**: {self.score['score']:.1f}/{self.score['total']:.1f} ({self.score['percentage']:.2f}%)",
            "",
            "### Category Scores",
            "",
            "| Category | Score | Total | Percentage |",
            "|----------|-------|-------|------------|",
        ]
        for cat, cat_score in self.score.get("by_category", {}).items():
            lines.append(
                f"| {cat} | {cat_score['score']:.1f} | {cat_score['total']:.1f} | {cat_score['percentage']:.2f}% |"
            )
        lines.append("")
        lines.append("## Checks")
        lines.append("")
        lines.append("| Status | Category | Check | Path | Details |")
        lines.append("|--------|----------|-------|------|---------|")
        for r in self.results:
            status_emoji = {
                "PASS": "✅",
                "FAIL": "❌",
                "WARNING": "⚠️",
                "ERROR": "🔴",
                "SKIP": "⏭️",
            }.get(r.status, r.status)
            lines.append(
                f"| {status_emoji} {r.status} | {r.category} | {r.description} | `{r.path or ''}` | {r.details or ''} |"
            )
        lines.append("")
        lines.append("## Recommendations")
        lines.append("")
        # Generate recommendations based on failures
        fails = [r for r in self.results if r.status == "FAIL"]
        if fails:
            lines.append("### Critical Issues")
            for f in fails[:10]:
                lines.append(f"- **{f.description}** (`{f.path}`): {f.details}")
        warnings = [r for r in self.results if r.status == "WARNING"]
        if warnings:
            lines.append("")
            lines.append("### Suggested Improvements")
            for w in warnings[:10]:
                lines.append(f"- **{w.description}** (`{w.path}`): {w.details}")
        lines.append("")
        lines.append("---")
        lines.append("*Generated by Repository Audit Tool*")
        return "\n".join(lines)

    def to_console(self) -> str:
        """Generate console‑friendly report."""
        lines = []
        lines.append("=" * 60)
        lines.append("REPOSITORY AUDIT REPORT")
        lines.append("=" * 60)
        lines.append(f"Repository: {self.auditor.repo_path}")
        lines.append(f"Time: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}")
        lines.append(f"Checks run: {len(self.results)}")
        lines.append("")
        lines.append("SUMMARY")
        lines.append("-" * 60)
        lines.append(
            f"Overall: {self.score['score']:.1f}/{self.score['total']:.1f} ({self.score['percentage']:.2f}%)"
        )
        for cat, cat_score in self.score.get("by_category", {}).items():
            lines.append(
                f"  {cat}: {cat_score['score']:.1f}/{cat_score['total']:.1f} ({cat_score['percentage']:.2f}%)"
            )
        lines.append("")
        lines.append("DETAILED RESULTS")
        lines.append("-" * 60)
        for r in self.results:
            status = r.status.ljust(8)
            lines.append(f"[{status}] {r.description}")
            if r.path:
                lines.append(f"      Path: {r.path}")
            if r.details:
                lines.append(f"      Note: {r.details}")
            lines.append("")
        return "\n".join(lines)

    def save(self, path: Union[str, Path], format: str = "markdown") -> Path:
        """Save report to file."""
        path = Path(path)
        if format == "json":
            content = self.to_json()
            suffix = ".json"
        elif format == "markdown":
            content = self.to_markdown()
            suffix = ".md"
        else:
            content = self.to_console()
            suffix = ".txt"
        if not path.suffix:
            path = path.with_suffix(suffix)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        return path
