[Licenses]
authorized_licenses:
    Apache-2.0
    BSD-3-Clause
    BSD-2-Clause
    MIT
    ISC
    Python-2.0
    Unlicense
    MPL-2.0
    LGPL-2.1-only
    LGPL-2.1-or-later
    LGPL-3.0-only
    LGPL-3.0-or-later
    GPL-2.0-only
    GPL-2.0-or-later
    GPL-3.0-only
    GPL-3.0-or-later

authorized_packages:
    pytest:MIT
    coverage:Apache-2.0
    black:MIT
    ruff:MIT

[General]
# Strictness level: can be STRICT, CAUTIOUS, LAX
strictness = CAUTIOUS
