# Webhooks configuration
# For more information, see https://sourcecraft.dev/portal/docs/sourcecraft/concepts/webhooks

# Example configuration:
# webhooks:
#   hooks:
#     - slug: test-webhook
#       name: "My test webhook"
#       description: "Triggered on main branch pushes"
#       url: "http://<webhook_server_IP_address>:5000/webhook"
#       ssl_verification: false
#       active: true
#
#   on:
#     repository.push:
#       - hooks: ["test-webhook"]
