apiVersion: v1
kind: Service
metadata:
  name: career-development
  namespace: portfolio
spec:
  type: ClusterIP
  selector:
    app: career-development
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
