apiVersion: v1
kind: Service
metadata:
  name: system-proof
  namespace: portfolio
spec:
  type: ClusterIP
  selector:
    app: system-proof
  ports:
  - port: 8003
    targetPort: 8003
    protocol: TCP
